spring.application.name=interviewmanagement-service

#  DATABASE CONFIG (H2)

spring.datasource.url=jdbc:h2:file:./data/interview-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#  H2 CONSOLE

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# = LIQUIBASE

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml



server.port=8080
